name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
                    
    - name: Set up CMake
      uses: threeal/cmake-action@v2.0.0

    - name: Install dependencies
      run: |
        choco install gperf cmake --install-args "'/InstallDir=C:\Program Files\gperf'"
        echo "gperf path:" $(where gperf)

    - name: Configure CMake
      env:
        GPERF_EXECUTABLE: "C:\\Program Files\\gperf\\gperf.exe"
      run: cmake -B build -S . -DGPERF_EXECUTABLE:FILEPATH="C:\\Program Files\\gperf\\gperf.exe"

    - name: Build
      run: cmake --build build --config Release

